# Generated by Django 6.0.3 on 2026-04-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=255, verbose_name='Слоган')),
                ('about_text', models.TextField(verbose_name='Обо мне')),
                ('about_photo', models.ImageField(upload_to='site/', verbose_name='Фото фотографа')),
                ('vk', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('tg', models.URLField(blank=True, verbose_name='Telegram')),
                ('inst', models.URLField(blank=True, verbose_name='Instagram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
