# Generated by Django 6.0.3 on 2026-04-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='slogan_bg',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Фон слогана'),
        ),
    ]
